### ISSUE TITLE
`pod try` doesn't work

### ISSUE THREAD

**Issue by aaronbrethorst** [Yalantis/Preloader.Ophiuchus#1]
the build fails, please check and then resubmit to cocoa controls

**Comment by IgorMuzyka** [comment]
@aaronbrethorst checked - the problem is that currnetly github is under a [DDOS attack](https://status.github.com/messages) which leads to pods being unable to download anything via https protocol. I'll update trunk and resubmit to cocoapods as soon as DDOS attack will end.

**Comment by aaronbrethorst** [comment]
I don't think that's it.

```
clang: error: no such file or directory: '/tmp/CocoaPods/Try/Ophiuchus/Example/Pods/Target Support Files/Pods-Ophiuchus-Ophiuchus/Pods-Ophiuchus-Ophiuchus-prefix.pch'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```

**Comment by IgorMuzyka** [comment]
@aaronbrethorst On it

**Comment by IgorMuzyka** [comment]
@aaronbrethorst fixed.

**Comment by aaronbrethorst** [comment]
awesome, thanks :+1:
